services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    env_file:
      - src/.env
    volumes:
      - ./src:/app/src
      - ./translations.json:/app/translations.json
    restart: unless-stopped